FROM mcr.microsoft.com/devcontainers/javascript-node:latest

VOLUME /src

WORKDIR /src
COPY . /src

RUN chown -R node:node /src && chmod 770 /src &&\
    chmod u+x /src/.devcontainer/apache-age-viewer/setup.sh

CMD ["sleep", "infinity"]

EXPOSE 3000
EXPOSE 3001
