FROM mcr.microsoft.com/devcontainers/javascript-node:latest

USER root
RUN chown node:node /src

USER node
COPY .devcontainer/apache-age-viewer/setup.sh /src/setup.sh

WORKDIR /src
COPY . /src

RUN chmod +x /src/setup.sh
# && /src/setup.sh

CMD ["sleep", "infinity"]

EXPOSE 3000
EXPOSE 3001
