FROM mcr.microsoft.com/devcontainers/javascript-node:latest

COPY setup.sh /src/setup.sh

WORKDIR /src
COPY . /src

RUN chmod +x /src/setup.sh && /src/setup.sh

CMD ["sleep", "infinity"]

EXPOSE 3000
EXPOSE 3001