FROM mcr.microsoft.com/devcontainers/javascript-node:latest

VOLUME /src

WORKDIR /src

COPY .devcontainer/apache-age-viewer/setup.sh /src/.devcontainer/apache-age-viewer/setup.sh
RUN chmod +x /src/.devcontainer/apache-age-viewer/setup.sh

CMD ["sleep", "infinity"]

EXPOSE 3000
EXPOSE 3001